
        function testErrorThrowsExceptionAndLogsOutput()
            nope:Nope()
        end